version: '3.8'

services:
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12341234
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  pg_data:
  minio_data: