version: '3.8'

#networks:
#  app-tier:
#    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12341234
      MINIO_DEFAULT_BUCKETS: default-bucket:private, second-default-bucket
    volumes:
      - minio_data:/bitnami/minio/data

      #      - MINIO_DEFAULT_BUCKETS=my-first-bucket:policy,my-second-bucket
      #    volumes:
      #      - --volume /path/to/minio-persistence:/bitnami/minio/data \
      #      - MINIO_CONSOLE_PORT_NUMBER=9001
  #    networks:
  #      - app-tier

  #    myapp:
  #      image: 'YOUR_APPLICATION_IMAGE'
  #      networks:
  #        - app-tier
  #      environment:
  #        - MINIO_SERVER_ACCESS_KEY=minio-access-key
  #        - MINIO_SERVER_SECRET_KEY=minio-secret-key

  mysql:
    image: 'mysql:8.2'
    restart: always
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  minio_data: