version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12341234
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

#  createbuckets:
#    image: minio/mc
#    depends_on:
#      - minio
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config host add myminio http://minio:9000 minio 12341234;
#      /usr/bin/mc rm -r --force myminio/user-files;
#      /usr/bin/mc mb myminio/user-files;
#      /usr/bin/mc policy download myminio/user-files;
#      exit 0;
#      "
  mysql:
    image: 'mysql:8.2'
    restart: always
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  minio_data: